use std::{
    collections::HashSet,
    fs::OpenOptions,
    io::Write,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context};

use crate::config::{provider_presets, AuthMode, ProviderPresetView, CONFIG_FILENAMES};

/// Declaring `[[upstreams]]` replaces the built-in provider set entirely, while
/// `server.default_provider` keeps its `anthropic` default. A starter that names
/// upstreams must therefore carry an `anthropic` passthrough upstream, or the
/// generated file fails `shunt check` (`default_provider references unknown
/// provider: anthropic`) and unmapped models lose their documented Anthropic
/// fallback.
const ANTHROPIC_PRESET: &str = "anthropic";

const HEADER: &str = "# shunt.toml — Claude Code LLM gateway configuration.\n\
# Generated by `shunt init`. Validate with `shunt check`; start with `shunt run`.\n\
# Reference: https://shunt.dev/guides/configuration/\n\n";
const DEFAULT_BODY: &str = "# An empty config is already a working gateway: unmapped models pass\n\
# through to Anthropic with your client's own credential.\n\n\
# Declare upstreams in failover order. Scaffold entries with\n\
# `shunt init --upstream <preset>`, or ask an agent: `shunt add upstream`.\n\
#\n\
# [[upstreams]]\n\
# name = \"codex\"\n\
# provider = \"codex\"  # preset: OpenAI Responses backend, ChatGPT OAuth (`shunt login codex`)\n\n\
# Map a public model id onto upstream backends:\n\
#\n\
# [[models]]\n\
# id = \"gpt-5.6-sol\"\n\
# [models.upstream_model]\n\
# codex = \"gpt-5.6-sol\"\n";

/// Create a starter `shunt.toml` and return the path written.
pub fn write_starter(
    root: Option<&Path>,
    upstream_names: &[String],
    force: bool,
) -> anyhow::Result<PathBuf> {
    let root = resolve_root(root)?;
    let presets = with_passthrough_fallback(resolve_presets(upstream_names)?);
    let existing = existing_configs(&root)?;
    if !force && !existing.is_empty() {
        let names = existing
            .iter()
            .filter_map(|path| path.file_name())
            .map(|name| name.to_string_lossy())
            .collect::<Vec<_>>()
            .join(", ");
        bail!("configuration file(s) already exist: {names}; use --force to write shunt.toml");
    }

    let path = root.join("shunt.toml");
    let body = render_starter(&presets);
    if force {
        // Atomically replace any existing config: render into a private sibling
        // temp, then rename it over `shunt.toml`. Exclusive temp creation plus the
        // rename never follow a symlink at the target — so `--force` cannot be
        // raced into truncating a file outside `root` — and the previous config
        // survives a failed write because the rename only swaps in a file that was
        // written and flushed in full.
        crate::atomic_file::write_private_atomic_in_existing_dir(&path, body.as_bytes())
            .with_context(|| format!("failed to write {}", path.display()))?;
    } else {
        // `create_new` refuses to clobber or follow a symlink, so a file that
        // appears after the existing-config guard cannot be overwritten.
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
            .with_context(|| format!("failed to create {}", path.display()))?;
        file.write_all(body.as_bytes())
            .with_context(|| format!("failed to write {}", path.display()))?;
        file.flush()
            .with_context(|| format!("failed to write {}", path.display()))?;
    }
    Ok(path)
}

fn resolve_root(root: Option<&Path>) -> anyhow::Result<PathBuf> {
    let root = match root {
        Some(root) => root.to_path_buf(),
        None => std::env::current_dir().context("failed to resolve current directory")?,
    };
    let metadata = std::fs::metadata(&root)
        .with_context(|| format!("root directory does not exist: {}", root.display()))?;
    if !metadata.is_dir() {
        bail!("root path is not a directory: {}", root.display());
    }
    Ok(root)
}

fn existing_configs(root: &Path) -> anyhow::Result<Vec<PathBuf>> {
    let mut existing = Vec::new();
    for name in CONFIG_FILENAMES {
        let path = root.join(name);
        match std::fs::symlink_metadata(&path) {
            Ok(_) => existing.push(path),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => {
                return Err(error).with_context(|| format!("failed to inspect {}", path.display()));
            }
        }
    }
    Ok(existing)
}

fn resolve_presets(names: &[String]) -> anyhow::Result<Vec<ProviderPresetView>> {
    let available = provider_presets().collect::<Vec<_>>();
    let available_names = available
        .iter()
        .map(|preset| preset.name)
        .collect::<Vec<_>>()
        .join(", ");
    let mut seen = HashSet::new();
    let mut selected = Vec::with_capacity(names.len());

    for name in names {
        if !seen.insert(name.as_str()) {
            bail!("duplicate upstream preset {name:?}");
        }
        let preset = available
            .iter()
            .find(|preset| preset.name == name)
            .copied()
            .ok_or_else(|| {
                anyhow::anyhow!(
                    "unknown upstream preset {name:?}; available presets: {available_names}"
                )
            })?;
        selected.push(preset);
    }
    Ok(selected)
}

/// Append an `anthropic` passthrough upstream unless the caller already asked for
/// one, so a preset-based starter validates and keeps the default_provider
/// fallback (see [`ANTHROPIC_PRESET`]). Left untouched when no presets were
/// requested: an empty starter is all comments and already passes through.
fn with_passthrough_fallback(mut presets: Vec<ProviderPresetView>) -> Vec<ProviderPresetView> {
    if presets.is_empty() || presets.iter().any(|preset| preset.name == ANTHROPIC_PRESET) {
        return presets;
    }
    let anthropic = provider_presets()
        .find(|preset| preset.name == ANTHROPIC_PRESET)
        .expect("anthropic passthrough preset must exist in the registry");
    presets.push(anthropic);
    presets
}

fn render_starter(presets: &[ProviderPresetView]) -> String {
    if presets.is_empty() {
        return format!("{HEADER}{DEFAULT_BODY}");
    }

    let mut output = String::from(HEADER);
    output.push_str("# Declare upstreams in failover order.\n\n");
    for preset in presets {
        output.push_str("# credential: ");
        output.push_str(&credential_source(*preset));
        output.push_str("\n[[upstreams]]\nname = \"");
        output.push_str(preset.name);
        output.push_str("\"\nprovider = \"");
        output.push_str(preset.name);
        output.push_str("\"\n\n");
    }

    output.push_str("# Map a public model id onto upstream backends:\n#\n");
    output.push_str("# [[models]]\n# id = \"model-id\"\n# [models.upstream_model]\n# ");
    output.push_str(presets[0].name);
    output.push_str(" = \"upstream-model-id\"\n");
    output
}

fn credential_source(preset: ProviderPresetView) -> String {
    match preset.auth {
        AuthMode::ApiKey => match preset.api_key_env {
            Some(env) => format!("requires ${env} in the environment."),
            None => "requires an API key in the environment.".to_string(),
        },
        AuthMode::ChatgptOauth => "`shunt login codex`.".to_string(),
        AuthMode::XaiOauth => "`shunt login xai`.".to_string(),
        AuthMode::CursorOauth => "`shunt login cursor`.".to_string(),
        AuthMode::CommandCodeOauth => {
            "a read-only Command Code subscription credential ($SHUNT_COMMAND_CODE_TOKEN)."
                .to_string()
        }
        AuthMode::KimiOauth => "`shunt login kimi --name <account-name>`.".to_string(),
        AuthMode::Passthrough => {
            "passes the client's own Anthropic credential through.".to_string()
        }
        AuthMode::ClaudeOauth => "a configured Claude OAuth account.".to_string(),
        AuthMode::GoogleOauth => "a Gemini CLI Google OAuth login.".to_string(),
        AuthMode::AntigravityOauth => "`shunt login antigravity`.".to_string(),
        AuthMode::None => "uses no HTTP credential (local adapter).".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct TempDir(PathBuf);

    impl TempDir {
        fn new(tag: &str) -> Self {
            let path = std::env::temp_dir().join(format!(
                "shunt-init-{tag}-{}-{}",
                std::process::id(),
                SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .expect("clock after epoch")
                    .as_nanos()
            ));
            std::fs::create_dir_all(&path).expect("create temp directory");
            Self(path)
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn default_starter_loads_as_default_config() {
        let dir = TempDir::new("default");
        let path = write_starter(Some(&dir.0), &[], false).unwrap();

        let config = Config::load(Some(&path)).unwrap();
        assert!(config.upstreams.is_empty());
        assert_eq!(
            std::fs::read_to_string(path).unwrap(),
            format!("{HEADER}{DEFAULT_BODY}")
        );
    }

    #[test]
    fn starter_with_all_presets_loads_and_preserves_order() {
        let dir = TempDir::new("all-presets");
        let names = provider_presets()
            .map(|preset| preset.name.to_string())
            .collect::<Vec<_>>();
        let path = write_starter(Some(&dir.0), &names, false).unwrap();

        let config = Config::load(Some(&path)).unwrap();
        assert_eq!(config.upstream_order, names);
        let content = std::fs::read_to_string(path).unwrap();
        assert!(content.contains("requires $OPENAI_API_KEY in the environment"));
        assert!(content.contains("# anthropic = \"upstream-model-id\""));
        assert!(!content.contains("default_provider"));
    }

    #[test]
    fn force_overwrites_toml_but_preserves_yaml_variant() {
        let dir = TempDir::new("force");
        let toml = dir.0.join("shunt.toml");
        let yaml = dir.0.join("shunt.yaml");
        std::fs::write(&toml, "old toml").unwrap();
        std::fs::write(&yaml, "old yaml").unwrap();

        write_starter(Some(&dir.0), &[], true).unwrap();

        assert_ne!(std::fs::read_to_string(toml).unwrap(), "old toml");
        assert_eq!(std::fs::read_to_string(yaml).unwrap(), "old yaml");
    }

    #[test]
    fn rejects_unknown_and_duplicate_presets() {
        let unknown = resolve_presets(&["unknown".to_string()]).unwrap_err();
        assert!(unknown
            .to_string()
            .contains("available presets: anthropic, codex"));

        let duplicate = resolve_presets(&["codex".to_string(), "codex".to_string()]).unwrap_err();
        assert!(duplicate.to_string().contains("duplicate upstream preset"));
    }

    #[test]
    fn preset_starter_appends_anthropic_fallback_and_passes_validation() {
        let dir = TempDir::new("fallback");
        let path = write_starter(
            Some(&dir.0),
            &["codex".to_string(), "kimi".to_string()],
            false,
        )
        .unwrap();

        // Loads *and validates*: the appended anthropic upstream keeps the
        // default_provider = "anthropic" fallback resolvable, so `shunt check`
        // (which calls validate()) no longer rejects the generated file.
        let config = Config::load(Some(&path)).unwrap().validate().unwrap();
        assert_eq!(config.upstream_order, ["codex", "kimi", "anthropic"]);

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("name = \"anthropic\""));
        assert!(content.contains("passes the client's own Anthropic credential through"));
        // Preserving the fallback must not silently divert unmapped traffic.
        assert!(!content.contains("default_provider"));
    }

    #[test]
    fn explicit_anthropic_request_is_not_duplicated() {
        let dir = TempDir::new("explicit-anthropic");
        let path = write_starter(
            Some(&dir.0),
            &["anthropic".to_string(), "codex".to_string()],
            false,
        )
        .unwrap();

        let config = Config::load(Some(&path)).unwrap().validate().unwrap();
        assert_eq!(config.upstream_order, ["anthropic", "codex"]);
    }

    #[test]
    fn forced_invalid_upstream_fails_before_touching_an_existing_config() {
        let dir = TempDir::new("forced-invalid");
        let toml = dir.0.join("shunt.toml");
        std::fs::write(&toml, "old toml").unwrap();

        // Preset validation runs before the destructive `--force` open, so an
        // unknown preset must not truncate the existing file.
        let error = write_starter(Some(&dir.0), &["unknown".to_string()], true).unwrap_err();
        assert!(error.to_string().contains("unknown upstream preset"));
        assert_eq!(std::fs::read_to_string(&toml).unwrap(), "old toml");
    }

    #[test]
    fn credential_source_covers_every_auth_mode() {
        let view = |auth, api_key_env| ProviderPresetView {
            name: "p",
            auth,
            api_key_env,
        };
        assert_eq!(
            credential_source(view(AuthMode::ApiKey, Some("OPENAI_API_KEY"))),
            "requires $OPENAI_API_KEY in the environment."
        );
        assert_eq!(
            credential_source(view(AuthMode::ApiKey, None)),
            "requires an API key in the environment."
        );
        assert_eq!(
            credential_source(view(AuthMode::ChatgptOauth, None)),
            "`shunt login codex`."
        );
        assert_eq!(
            credential_source(view(AuthMode::XaiOauth, None)),
            "`shunt login xai`."
        );
        assert_eq!(
            credential_source(view(AuthMode::CursorOauth, None)),
            "`shunt login cursor`."
        );
        assert_eq!(
            credential_source(view(AuthMode::KimiOauth, None)),
            "`shunt login kimi --name <account-name>`."
        );
        assert_eq!(
            credential_source(view(AuthMode::Passthrough, None)),
            "passes the client's own Anthropic credential through."
        );
        assert_eq!(
            credential_source(view(AuthMode::ClaudeOauth, None)),
            "a configured Claude OAuth account."
        );
    }

    #[cfg(unix)]
    #[test]
    fn force_replaces_a_symlink_without_touching_its_target() {
        use std::os::unix::fs::symlink;

        let dir = TempDir::new("force-symlink");
        let victim = dir.0.join("victim.txt");
        std::fs::write(&victim, "victim contents").unwrap();
        let link = dir.0.join("shunt.toml");
        symlink(&victim, &link).unwrap();

        // The atomic replace never follows the link: it swaps the `shunt.toml`
        // entry for a real file and leaves the link target untouched, closing the
        // symlink-follow / TOCTOU hazard the old truncate path had.
        let path = write_starter(Some(&dir.0), &[], true).unwrap();
        assert_eq!(path, link);
        assert_eq!(std::fs::read_to_string(&victim).unwrap(), "victim contents");
        let meta = std::fs::symlink_metadata(&link).unwrap();
        assert!(meta.file_type().is_file());
        assert!(std::fs::read_to_string(&link)
            .unwrap()
            .contains("shunt.toml"));
    }
}
